#!/bin/bash

# Description: Echos color of fruit

if [[ -z $1 ]]; then
	echo "Usage: $0 <fruit>" >&2
	exit 1
fi

case $1 in
	apple)
		echo "Red"
		;;
	banana)
		echo "Yellow"
		;;
	kiwi)
		echo "Brown"
		;;
	*)
		echo "Unknown fruit: $1" >&2
		exit 1
		;;
esac
